Aws lz overview
bcgov/public-cloud-techdocs pull request #10
Opened 2023-11-10 23:54 UTC by wrnu

closes: bcgov/cloud-pathfinder#2752

2023-11-15 22:07 UTC, Pilargit12 commented on docs/iam-user-service.md
> +<!-- Related pages need to be added here  -->
Please make sure to add any supporting documents or links that can help users obtain help related to the topic

2023-11-15 22:11 UTC, Pilargit12 commented on docs/bc-govs-aws-landing-zone-overview.md
> +<!-- - TODO: Link to the networking page -->
Add missing link

2023-11-15 22:13 UTC, Pilargit12 commented on docs/git-error-1700083265273
> +Aborting
This was the error that happened before Warren's last pull - I believe can be deleted.

2023-11-15 22:14 UTC, Pilargit12 requested changes
Hi there, the review has been completed. I made a few comments for your revision before this can be merged to main. Thank you!

2023-11-16 18:48 UTC, MaxWardle commented on docs/bc-govs-aws-landing-zone-overview.md
> +<!-- - TODO: Link to the security guardrails page -->
I think this will be the page I'm creating now, so it'll be added in the future :)

2023-11-16 18:52 UTC, MaxWardle commented on docs/bc-govs-aws-landing-zone-overview.md
> +<!-- - TODO: Link to the networking page -->
This one too

2023-11-16 19:32 UTC, merged