Reqs for app
bcgov/public-cloud-techdocs pull request #17
Opened 2023-12-18 22:54 UTC by abibat-adesina

I included local deployment paragraph

2023-12-18 23:15 UTC, wrnu requested changes
The content of the document is great! Thanks @abibat-adesina .

A have left a few comments for a few changes that are needed.

Also this branch is behind the `dev` branch, please pull in the latest changes

2023-12-18 23:15 UTC, wrnu commented on docs/mkdocs.yml
This file should be removed, it is not needed, there is a mkdoc.yml in the root that should be used. Make sure to add this new page to that file.

2023-12-18 23:15 UTC, wrnu commented on docs/package-lock.json
This file should be removed

2023-12-18 23:15 UTC, wrnu commented on docs/package.json
this file should be removed

2023-12-18 23:15 UTC, wrnu commented on .DS_Store
This file should be removed, there is one in the root that can be removed as well.

Please add a .gitignore file to the root and put `.DS_Store` in it

2023-12-18 23:15 UTC, wrnu commented on docs/requirements-for-building-your-application.md
> +Last updated: **November 27, 2023**
This isn't so important but we can update the date :)

2023-12-18 23:57 UTC, abibat-adesina commented on docs/mkdocs.yml
How do I add this new page to mkdoc.yml in the root

2023-12-19 01:00 UTC, abibat-adesina commented on docs/mkdocs.yml
I have seen how to add the new page to mkdoc.yml in the root

2023-12-19 03:10 UTC, abibat-adesina commented
All changes made

2023-12-19 18:04 UTC, wrnu approved these changes
Looks good :+1:

2023-12-19 22:43 UTC, Pilargit12 requested changes
Left a comment in the new PR push - line 47-53 to be addressed as per your expertise, however I believe for the reader it would be helpful to provide further detail. Thanks!

2024-01-08 20:04 UTC, abibat-adesina commented
I added more info that might be helpful to the reader

2024-01-09 18:01 UTC, Pilargit12 commented on docs/requirements-for-building-your-application.md
> +  -->
This is the part that needs last revision @abibat-adesina  - thank you so much!

2024-01-13 10:07 UTC, abibat-adesina reviewed
@wrnu @Pilargit12 
Related: bcgov/cloud-pathfinder#2700

2024-01-16 18:14 UTC, wrnu approved these changes

2024-01-22 20:33 UTC, Pilargit12 approved these changes
Hi @abibat-adesina - new pull contains just a few corrections but should be good to go! Thanks!

2024-01-22 21:01 UTC, merged